[package]
name = "adder-ffi"
version = "0.1.0"
authors = ["Shady Khalifa <shekohex@gmail.com>"]
edition = "2018"

[lib]
name = "adder_ffi"
crate-type = ["rlib"]

[dependencies]
adder = { path = "../adder" }

[build-dependencies]
cbindgen = "0.14.3"