name: adder
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^2.4.0

ffigen:
    output: 'lib/binding.dart'
    headers:
      entry-points:
        - 'binding.h'
    llvm-path: 
      - '/usr/lib'
      - '/home/misha/Desktop/llvm/lib/'
      - '/home/misha/Desktop/llvm/bin/'
      - '/home/misha/Desktop/llvm/'
      - '/home/misha/Desktop/llvm/lib/clang/11.0.1/lib/linux/'

flutter:
  plugin:
    androidPackage: com.example.adder
    pluginClass: AdderPlugin
